// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVWpAYlnzfqof4WuSnzZSYjcK-tc2GpfM',
    appId: '1:656868007744:web:35c67a1bdbcf28272624a5',
    messagingSenderId: '656868007744',
    projectId: 'domenow',
    authDomain: 'domenow.firebaseapp.com',
    storageBucket: 'domenow.appspot.com',
    measurementId: 'G-LE1RL2CVL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHBxTt2cuZkxdN8tFGpICNkmKuWWnZ0w',
    appId: '1:656868007744:android:43f3d54b5eac73722624a5',
    messagingSenderId: '656868007744',
    projectId: 'domenow',
    storageBucket: 'domenow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjC7aBYwy-oChBwgpLt6oJ66a84lTDT4k',
    appId: '1:656868007744:ios:72bbb0c3f55f32c52624a5',
    messagingSenderId: '656868007744',
    projectId: 'domenow',
    storageBucket: 'domenow.appspot.com',
    iosBundleId: 'com.example.taskmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjC7aBYwy-oChBwgpLt6oJ66a84lTDT4k',
    appId: '1:656868007744:ios:72bbb0c3f55f32c52624a5',
    messagingSenderId: '656868007744',
    projectId: 'domenow',
    storageBucket: 'domenow.appspot.com',
    iosBundleId: 'com.example.taskmaker',
  );
}
